<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<PackageId>MinimalCommandLine.Core</PackageId>
		<Title>Minimal Command Line Core APIs</Title>
		<Authors>dotnetKyle</Authors>
		<Description>A set of minimal builders that sits on top of the System.CommandLine namespace to give an experience similar to the ASP.Net Core minimal API builders.</Description>
		<PackageProjectUrl></PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/dotnetKyle/MinimalCommandLine</RepositoryUrl>
		<PackageTags>Command; Line</PackageTags>
		<DebugType>embedded</DebugType>
		<RootNamespace>System.CommandLine.Minimal</RootNamespace>
		
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>obj\Generated</CompilerGeneratedFilesOutputPath>
		<IsRoslynComponent>true</IsRoslynComponent>
	</PropertyGroup>

</Project>
