<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<PackageId>MinimalCli</PackageId>
		<Title>Minimal Command Line</Title>
		<Authors>dotnetKyle</Authors>
		<Description>A source generator on top of System.CommandLine to minimize the boiler plate needed to get started. Just add a [Handler] attribute to a function to get started!</Description>
		<PackageProjectUrl></PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/dotnetKyle/MinimalCli</RepositoryUrl>
		<PackageTags>Command; Line; System.CommandLine; Minimal; Source Generator; Minimal CLI; CLI</PackageTags>
		<PackageReleaseNotes>Added a source generator to quickly rig up commands with minimal effort.</PackageReleaseNotes>
		<DebugType>embedded</DebugType>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<!-- Runtime library -->
		<Content Include="..\MinimalCli.Core\bin\$(Configuration)\netstandard2.0\MinimalCli.Core.dll" Pack="true" PackagePath="lib/netstandard2.0/" />

		<!-- Source generator library -->
		<Content Include="..\MinimalCli.SourceGenerator\bin\$(Configuration)\netstandard2.0\MinimalCli.SourceGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs/" />
	</ItemGroup>
	
	<ItemGroup>
		<!-- Runtime library nuget dependencies -->
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="System.CommandLine" Version="2.0.3" />
	</ItemGroup>
</Project>
