<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<PackageId>MinimalCommandLine.SourceGenerator</PackageId>
		<Title>Minimal Command Line Source Generator</Title>
		<Authors>dotnetKyle</Authors>
		<Description>A source generator for MinimalCommandLine. Enables the quick rigging of commands using a Command attribute.</Description>
		<PackageProjectUrl></PackageProjectUrl>
		<RepositoryUrl>https://github.com/dotnetKyle/MinimalCommandLine</RepositoryUrl>
		<PackageTags>Command; Line</PackageTags>
		<DebugType>embedded</DebugType>

		<IsRoslynAnalyzer>true</IsRoslynAnalyzer>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>obj\Generated</CompilerGeneratedFilesOutputPath>
		<IsRoslynComponent>true</IsRoslynComponent>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\System.CommandLine.Minimal.Core\System.CommandLine.Minimal.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
