name: PR-Checks

on:
  pull_request:
    # Runs on all branches so they share a github.run_number increment
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/System.CommandLine.Minimal.sln
      
    - name: Build Minimal CommandLine
      run: dotnet build src/System.CommandLine.Minimal.sln -c Release --no-restore -f net6.0
